name: widget_wave
repository: https://github.com/xsahil03x/widget_wave

packages:
  - packages/flutter_svg_icon

command:
  bootstrap:
    environment:
      sdk: ^3.5.0
      flutter: ">=3.24.0"

    dependencies:
      flutter_svg: ^2.0.17

    dev_dependencies:
      flutter_lints: ^4.0.0

  version:
    branch: main
    linkToCommits: true
    workspaceChangelog: true

  clean:
    hooks:
      post: melos exec -c 1 --flutter -- "flutter clean"


scripts:
  analyze:
    run: melos exec -c 1 -- "flutter analyze . --no-congratulate"
    description: Run `flutter analyze` in all packages.

  analyze:changes:
    run: melos exec -c 1 --diff=origin/main...HEAD -- "flutter analyze . --no-congratulate"
    description: Run `flutter analyze` in all changed packages.

  test:
    run: melos exec -c 1 --dir-exists=test -- "flutter test --no-pub --coverage"
    description: Run `flutter test` in all packages.

  test:changes:
    run: melos exec -c 1 --dir-exists=test --diff=origin/main...HEAD -- "flutter test --no-pub --coverage"
    description: Run `flutter test` in all changed packages.

  format:
    run: melos exec -c 1 -- "dart format . --set-exit-if-changed"
    description: Run `flutter format` in all packages.

  format:changes:
    run: melos exec -c 1 --diff=origin/main...HEAD -- "dart format . --set-exit-if-changed"
    description: Run `flutter format` in all changed packages.
