name: flex_grid_example
description: Example for the flex_grid package.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flex_grid:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter