name: flutter_svg_icon
description: A Flutter package that provides a simple way to use SVG icons in your Flutter app.
version: 0.0.1
homepage: https://github.com/xsahil03x/widget_wave/packages/flutter_svg_icon
repository: https://github.com/xsahil03x/widget_wave/packages/flutter_svg_icon
issue_tracker: https://github.com/xsahil03x/widget_wave/issues

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - svg
  - icon
  - svg-icon
  - flutter-svg
  - flutter-icon

screenshots:
  - description: 'Flutter SVG Icon Showcase'
    path: assets/showcase.png