name: flutter_svg_icon
description: "A new Flutter project."
version: 0.0.1
homepage: https://github.com/xsahil03x/widget_wave/packages/flutter_svg_icon

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter